//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

pub mod prelude;

pub mod actions;
pub mod audit_logs;
pub mod login_attempts;
pub mod notifications;
pub mod password_resets;
pub mod permission_actions;
pub mod permissions;
pub mod post;
pub mod resources;
pub mod role_permissions;
pub mod roles;
pub mod sessions;
pub mod user_roles;
pub mod users;
