//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "permissions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub resource_id: Uuid,
    #[sea_orm(
        belongs_to,
        from = "resource_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub resources: HasOne<super::resources::Entity>,
    #[sea_orm(has_many, via = "permission_actions")]
    pub actions: HasMany<super::actions::Entity>,
    #[sea_orm(has_many, via = "role_permissions")]
    pub roles: HasMany<super::roles::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
