//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "permission_actions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub permission_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub action_id: Uuid,
    pub allowed: bool,
    #[sea_orm(
        belongs_to,
        from = "action_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub actions: HasOne<super::actions::Entity>,
    #[sea_orm(
        belongs_to,
        from = "permission_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub permissions: HasOne<super::permissions::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
