//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

pub use super::actions::Entity as Actions;
pub use super::audit_logs::Entity as AuditLogs;
pub use super::login_attempts::Entity as LoginAttempts;
pub use super::notifications::Entity as Notifications;
pub use super::password_resets::Entity as PasswordResets;
pub use super::permission_actions::Entity as PermissionActions;
pub use super::permissions::Entity as Permissions;
pub use super::post::Entity as Post;
pub use super::resources::Entity as Resources;
pub use super::role_permissions::Entity as RolePermissions;
pub use super::roles::Entity as Roles;
pub use super::sessions::Entity as Sessions;
pub use super::user_roles::Entity as UserRoles;
pub use super::users::Entity as Users;
