//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub username: String,
    #[sea_orm(unique)]
    pub email: String,
    pub password: String,
    pub status: String,
    pub is_banned: bool,
    pub avatar_url: Option<String>,
    pub last_active: Option<DateTime>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub notifications: HasMany<super::notifications::Entity>,
    #[sea_orm(has_many)]
    pub password_resets: HasMany<super::password_resets::Entity>,
    #[sea_orm(has_many)]
    pub sessions: HasMany<super::sessions::Entity>,
    #[sea_orm(has_many, via = "user_roles")]
    pub roles: HasMany<super::roles::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
